version: '3.8'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend/app:/app/app
      - straydogs-db-data:/app/straydogs.db
    ports:
      - "8000:8000"
    environment:
      - TZ=UTC
    restart: unless-stopped
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build:
      context: ./mobile
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - ./mobile:/app
      # This prevents the host node_modules from overwriting the container's
      - /app/node_modules
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
    command: npx expo start --tunnel
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  straydogs-db-data:
