version: '3.8'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend/app:/app/app
      - ./data/db:/app/data
    ports:
      - "8000:8000"
    environment:
      - TZ=UTC
      - SQLITE_DB_PATH=/app/data/straydogs.db
    restart: unless-stopped
    command: >
      sh -c "mkdir -p /app/data && \
             touch /app/data/straydogs.db && \
             chmod 666 /app/data/straydogs.db && \
             uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  frontend:
    build:
      context: ./mobile
      dockerfile: Dockerfile
    ports:
      - "19000:19000"  # Expo dev server
      - "19001:19001"  # Expo dev tools
      - "19002:19002"  # React Native dev tools
      - "19006:19006"  # Expo dev menu
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.1.5
    volumes:
      - ./mobile:/app
      - /app/node_modules
    command: npx expo start --lan
    depends_on:
      - backend
    restart: unless-stopped
