apiVersion: apps/v1
kind: Deployment
metadata:
  name: straydog-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: straydog-backend
  template:
    metadata:
      labels:
        app: straydog-backend
    spec:
      containers:
      - name: backend
        image: straydog-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: TZ
          value: UTC
        volumeMounts:
        - name: db-data
          mountPath: /app/straydogs.db
      volumes:
      - name: db-data
        emptyDir: {}
